apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mydotnetapp.fullname" . }}
  labels:
    {{- include "mydotnetapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mydotnetapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mydotnetapp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mydotnetapp.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http