name: Kubernetes Cluster

on:
  workflow_run:
    workflows: ["Build and Push Docker image"]
    types:
      - completed
    branches:
      - main
jobs:
  kind-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Kind Cluster
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster
        kubectl cluster-info --context kind-kind
    
    - name: Install MetalLB CRDs
      run: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/main/config/crd/bases/metallb.io_ipaddresspools.yaml
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/main/config/crd/bases/metallb.io_l2advertisements.yaml

    - name: Install MetalLB
      run: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
        kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

    - name: Wait for MetalLB CRDs to be ready
      run: |
        for crd in addresspools.metallb.io l2advertisements.metallb.io
        do
          echo "Waiting for $crd to be ready..."
          kubectl wait --for=condition=Established --timeout=60s crd/$crd
        done

    - name: Configure MetalLB
      run: |
        echo "apiVersion: metallb.io/v1
        kind: AddressPool
        metadata:
          name: default
          namespace: metallb-system
        spec:
          protocol: layer2
          addresses:
          - 172.17.0.100-172.17.0.250" | kubectl apply -f -
    
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Helm Chart
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm install mydotnetapp ./helm

    - name: Run Tests
      run: |
        echo 'Running: kubectl get nodes'
        kubectl get nodes
        sleep 5
        echo 'Running: kubectl get pods -A'
        kubectl get pods -A
        sleep 5
        echo 'Running: kubectl get deployments'
        kubectl get deployments
        sleep 5
        echo 'Running: kubectl get svc -A'
        kubectl get svc -A

    - name: Cleanup Cluster
      if: always()
      run: kind delete cluster
