name: Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  kind-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Kind Cluster
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster
        kubectl cluster-info --context kind-kind

    - name: Run Tests
      run: |
        # This is where you would add commands to deploy and test your application.
        kubectl get nodes
        kubectl apply -f your_k8s_config.yaml
        # Add more kubectl commands as needed for testing.

    - name: Cleanup Cluster
      if: always()
      run: kind delete cluster
