name: Kubernetes Cluster

on:
  workflow_run:
    workflows: ["Build and Push Docker image"]
    types:
      - completed
    branches:
      - main
jobs:
  kind-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Kind Cluster
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster
        kubectl cluster-info --context kind-kind
    
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Helm Chart
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm install mydotnetapp ./helm

    - name: Run Tests
      run: |
        kubectl get nodes
        # Add more kubectl commands as needed for testing.

    - name: Cleanup Cluster
      if: always()
      run: kind delete cluster
